### ISSUE TITLE
Getting compile error on iOS.

### ISSUE THREAD

**Issue by rollsroyc3** [rollsroyc3/opentok-titanium#2]
@billdawson 
Log output when trying to compile:

In file included from /Users/andrewroyce/Documents/projects/opentok-titanium/ios/Classes/ComTokboxTiOpentokPublisherProxy.m:7:
/Users/andrewroyce/Documents/projects/opentok-titanium/ios/Classes/ComTokboxTiOpentokSessionProxy.h:54:18: error: expected ';'
      after method prototype
- (void)setApiKey(id)key;
                 ^
                 ;
/Users/andrewroyce/Documents/projects/opentok-titanium/ios/Classes/ComTokboxTiOpentokSessionProxy.h:56:21: error: expected ';'
      after method prototype
- (void)setSessionId(id)value;
                    ^
                    ;
/Users/andrewroyce/Documents/projects/opentok-titanium/ios/Classes/ComTokboxTiOpentokPublisherProxy.m:88:47: warning: 
      'initWithDelegate:name:' is deprecated: Use initWithDelegate: settings: instead [-Wdeprecated-declarations]
            _publisher = [[OTPublisher alloc] initWithDelegate:self name:name];
                                              ^
In file included from /Users/andrewroyce/Documents/projects/opentok-titanium/ios/Classes/ComTokboxTiOpentokPublisherProxy.m:6:
In file included from /Users/andrewroyce/Documents/projects/opentok-titanium/ios/Classes/ComTokboxTiOpentokPublisherProxy.h:7:
In file included from /Users/andrewroyce/Documents/projects/opentok-titanium/ios/Opentok.framework/Headers/OpenTok.h:11:
In file included from /Users/andrewroyce/Documents/projects/opentok-titanium/ios/OpenTok.framework/Headers/OpenTokObjC.h:8:
/Users/andrewroyce/Documents/projects/opentok-titanium/ios/OpenTok.framework/Headers/OTPublisherKit.h:130:1: note: 
      'initWithDelegate:name:' has been explicitly marked deprecated here
- (nonnull instancetype)initWithDelegate:(nullable id<OTPublisherKitDelegate>)delegate
^
1 warning and 2 errors generated.

Image if that is easier:
https://www.dropbox.com/s/5i0yysyx2mj5cfn/Screenshot%202017-01-17%2016.37.09.png?dl=0

**Comment by billdawson** [comment]
Go ahead and retry (pull latest master).

**Comment by rollsroyc3** [comment]
Looks like some issues with retain. If any of these fixes will take a while please let me know first.

https://www.dropbox.com/s/04716obnxrjzqkj/Screenshot%202017-01-17%2017.03.12.png?dl=0

**Comment by billdawson** [comment]
Oh for some reason I thought this project was not using ARC.  Just a sec…

**Comment by billdawson** [comment]
Ready again.  Pull latest.

Note: the whole thing is still under one hour so far. :)

**Comment by rollsroyc3** [comment]
Getting closer!

https://www.dropbox.com/s/b3lr84yk68g6ru6/Screenshot%202017-01-17%2017.12.06.png?dl=0

**Comment by billdawson** [comment]
Wth. A double hash.  fixed :)

**Comment by rollsroyc3** [comment]
Compiles! I will be testing tomorrow and will keep you updated. Thanks for the quick work!
